### ISSUE TITLE
When attending offtopic conferences, give a "lightning" talk

### ISSUE THREAD

**Issue by skurfuerst** [neos/team#26]

**Comment by skurfuerst** [comment]
@markusguenther wanted to do one on T3Camp Berlin

**Comment by skurfuerst** [comment]
@rolandschuetz wanted to to a talk on at least one meetup

**Comment by rolandschuetz** [comment]
Already did one talk at a PHP meetup and [mentioned Neos at a JS event](https://viennajs.org/en/meetup/2019-06/page-load-performance-2014-and-now).

**Comment by markusguenther** [comment]
Ah should we list that here :)

- [TYPO3 Meetup Magdeburg](https://www.meetup.com/de-DE/TYPO3-UserGroup-Magdeburg/events/261831794/) (React Introduction): Showed Neos as example for a bigger React application
- [TYPO3camp Berlin](https://typo3camp-berlin.de/news/eindruecke-vom-t3cb-2019/) (Neos Introduction session and a second session as follow up)
- [DCX Expo Berlin](https://www.dcx-expo.com/programm/vortragsprogramm/event/headless-content-management-why-and-how/?tx_bmtheme_programm%5Bbackpid%5D=1019&cHash=7d8293abdcb80e4e6f78f206f9844c0b) (Panel discussion about Headless CMS)

**Comment by skurfuerst** [comment]
- was on a meetup in Rosenheim (WebDev Meetup), where I talked about Event Sourcing in context of Neos: https://www.meetup.com/de-DE/Web-Technology-Usergroup-WTUG-Rosenheim/events/261843394/
- will talk about Neos at Contao Meetup: https://www.meetup.com/de-DE/contao-stammtisch-dresden/events/257936614/
