### ISSUE TITLE
Call some neos Agencies to broaden the Neos reach

### ISSUE THREAD

**Issue by skurfuerst** [neos/team#29]

**Comment by rolandschuetz** [comment]
Done, called about 20 agencies. Nothing too interesting though.

**Comment by skurfuerst** [comment]
thanks <3 Maybe get back to @fabiantschoek to share experiences :)

**Comment by tschoeki** [comment]
@rolandschuetz nice! and as @skurfuerst mentioned, let's share our experiences :)
