### ISSUE TITLE
Organize release process topic sprint

### ISSUE THREAD

**Issue by robertlemke** [neos/team#5]
**Deliverable**
Organized topic sprint about release management.

**Until**
09.11.2018

@maragi will organize the event, @kdambekalns and @kitsunet help with the topics / communication.

**Comment by kdambekalns** [comment]
- a doodle on two potential dates has been opened: https://doodle.com/poll/byte8fra3b3q4bc4
- @maragi and @kdambekalns defined a rough outline

**Comment by kdambekalns** [comment]
The sprint has been set on January 15/16 by now.

**Comment by kdambekalns** [comment]
https://discuss.neos.io/t/release-process-topic-sprint-hamburg-january-15th-16th-2019/3971?u=kdambekalns
