### ISSUE TITLE
Move Neos UI to Neos Development Collection

### ISSUE THREAD

**Issue by robertlemke** [neos/team#8]
During the Fishbowl discussion in Salzburg the team decided to move the Neos UI code into the Neos Development Collection in order to synchronize releases (also marketing-wise) with Neos.

The merge / move should happen for the next Neos major release (5.0).

**Deliverable**
Make sure that this action is planned in for the Neos 5.0 release.

**Comment by Sebobo** [comment]
We went another way and synchronise the releases versions now. Therefore I close this task

**Comment by albe** [comment]
Is there any documented rationale on this decision to not go the mono-repo route with the UI? Would be interested!

**Comment by Sebobo** [comment]
@albe I think spread over several places in slack etc.

I think one of the main points was to be able to have more feature releases.
@dimaip is better informed.

**Comment by dimaip** [comment]
Oh no no, on the contrary, we wanted to get feature releases exactly in-sync.
The reason to keep it in separate repos is so it'd be easier for people who mostly do UI-only stuff to stay on top of notifications and issues.

**Comment by albe** [comment]
Okay, so purely organisatorial decision :) Thanks for clarifying!
